# Generated by Django 5.1 on 2024-10-23 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Locatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
                ('classificacao', models.DecimalField(decimal_places=2, max_digits=3)),
                ('link', models.URLField()),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoteis', to='ondeficar.locatario')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('localizacao', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('navio', 'Navio'), ('casa', 'Casa'), ('hotel', 'Hotel')], max_length=10)),
                ('descricao', models.TextField()),
                ('link', models.URLField()),
                ('classificacao', models.DecimalField(decimal_places=2, max_digits=3)),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='ondeficar.locatario')),
            ],
        ),
    ]
