# Generated by Django 5.1.2 on 2024-10-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondeficar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_hoteis/'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_lugares/'),
        ),
        migrations.DeleteModel(
            name='Hospede',
        ),
    ]
