# Generated by Django 5.1.2 on 2024-10-23 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondeficar', '0002_hotel_foto_lugar_foto_delete_hospede'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='locatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoteis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='locatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Locatario',
        ),
    ]
