# Generated by Django 5.1.2 on 2024-10-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondeficar', '0003_alter_hotel_locatario_alter_lugar_locatario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
