# Generated by Django 5.1.2 on 2024-10-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondeficar', '0004_hotelapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelApi',
        ),
        migrations.AddField(
            model_name='lugar',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
