# Generated by Django 5.1.2 on 2024-10-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondeficar', '0005_delete_hotelapi_lugar_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='classificacao',
            field=models.IntegerField(),
        ),
    ]
